### PR TITLE
Update dependencies

### PR DESCRIPTION
**Pull request by mserranom**
### Description

All dependencies are updated except

#### Manual Testing Performed

- [ ]
- [ ]

#### Deployment Checklist

- [ ] Update documentation not included in the PR (if any)
- [ ]

### CODE REVIEW

**Comment by jdleesmiller** [comment]
@mserranom There's still a big project ongoing to upgrade to socket.io v2 here (https://github.com/overleaf/real-time/tree/jpa-socket.io-v2). Please check with @das7pad before going further on this one. I would certainly be OK with doing these upgrades sequentially (this one after socket.io v2.)

**Comment by das7pad** [comment]
Yes, please delay until socket.io v2 has landed on master. It will complicate testing/debugging.

**Comment by mserranom** [comment]
Sure, I didn't plan to touch any `socket.io` dependency, only tests have been updated to match the latest `sinon` spec. It makes sense to proceed with:
- `socket.io` update
- dependency update (this PR)
- decaffeination, which is pending from decaffebruary. I'll do it straight after dependency updates

**Comment by 40thieves** [comment]
@mserranom I've moved this to Held while it's blocked. Please move it back if that's incorrect

**Comment by mserranom** [comment]
@das7pad are we stable enough to proceed with this?

**Comment by das7pad** [comment]
@mserranom no. We are not live for all users yet.

**Comment by mserranom** [comment]
Closing, replaced by https://github.com/overleaf/real-time/pull/157

**Pull request closed without merging**
