### PR TITLE
Decaffeinate real-time

### PR DESCRIPTION
**Pull request by gh2k**
### Description

Decaffeinate real-time

#### Related Issues / PRs

Part of overleaf/web-internal#2555

### Review

The `decaffeinate.sh` script worked fine. There were a few extra ESLint/Prettier bits to do at the end, which always seems to happen with the script.

#### Manual Testing Performed

- [ ] Edit a document in multiple tabs

### CODE REVIEW

**Comment by gh2k** [comment]
Let's put this on hold until after socket.io v2? cc @das7pad

**Comment by 40thieves** [comment]
@gh2k @das7pad Should this be in Held?

**Comment by ShaneKilkelly** [comment]
Could we update this PR, now that we've upgraded socket-io?

**Comment by das7pad** [comment]
> Could we update this PR, now that we've upgraded socket-io?

socket.io v2 has not landed on branch master yet.

**Comment by henryoswald** [comment]
should be good to go on this next week

**Pull request closed without merging**
